### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-linode#2]
Update note for cloning git repo

Clone:

Cloning with HTTPS URL

```sh
git clone https://github.com/turbot/steampipe-plugin-linode.git
cd steampipe-plugin-linode
```

Cloning with SSH URL (Refer [GitHub](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-ssh-urls))

```sh
git clone git@github.com:turbot/steampipe-plugin-linode.git
cd steampipe-plugin-linode
```

**Comment by misraved** [comment]
Fixed in - https://github.com/turbot/steampipe-plugin-linode/commit/9d50e8b26c541d610c38794088f645db463da300
